export const APPRENDRE_CREATE_REQUEST = 'INFO_CREATE_REQUEST'
export const APPRENDRE_CREATE_SUCCESS = 'INFO_CREATE_SUCCESS'
export const APPRENDRE_CREATE_FAIL = 'INFO_CREATE_FAIL'
export const APPRENDRE_CREATE_RESET = 'INFO_CREATE_RESET'


export const APPRENDRE_DELETE_REQUEST = 'INFO_DELETE_REQUEST'
export const APPRENDRE_DELETE_SUCCESS = 'INFO_DELETE_SUCCESS'
export const APPRENDRE_DELETE_FAIL = 'INFO_DELETE_FAIL'



export const APPRENDRE_LIST_REQUEST = 'INFO_LIST_REQUEST'
export const APPRENDRE_LIST_SUCCESS = 'INFO_LIST_SUCCESS'
export const APPRENDRE_LIST_FAIL = 'INFO_LIST_FAIL'



export const APPRENDRE_DETAILS_REQUEST = 'INFO_DETAILS_REQUEST'
export const APPRENDRE_DETAILS_SUCCESS = 'INFO_DETAILS_SUCCESS'
export const APPRENDRE_DETAILS_FAIL = 'INFO_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const APPRENDRE_UPDATE_REQUEST = 'INFO_UPDATE_REQUEST'
export const APPRENDRE_UPDATE_SUCCESS = 'INFO_UPDATE_SUCCESS'
export const APPRENDRE_UPDATE_FAIL = 'INFO_UPDATE_FAIL'
export const APPRENDRE_UPDATE_RESET = 'INFO_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'

export const APPRENDRE_UPDATE_STATUS_REQUEST = 'APPRENDRE_UPDATE_STATUS_REQUEST';
export const APPRENDRE_UPDATE_STATUS_SUCCESS = 'APPRENDRE_UPDATE_STATUS_SUCCESS';
export const APPRENDRE_UPDATE_STATUS_FAIL = 'APPRENDRE_UPDATE_STATUS_FAIL';

// actionTypes.js
export const UPDATE_APPRENDRE_STATUS_REQUEST = "UPDATE_APPRENDRE_STATUS_REQUEST";
export const UPDATE_APPRENDRE_STATUS_SUCCESS = "UPDATE_APPRENDRE_STATUS_SUCCESS";
export const UPDATE_APPRENDRE_STATUS_FAILURE = "UPDATE_APPRENDRE_STATUS_FAILURE";