export const ENTRAIDE_CREATE_REQUEST = 'ENTRAIDE_CREATE_REQUEST'
export const ENTRAIDE_CREATE_SUCCESS = 'ENTRAIDE_CREATE_SUCCESS'
export const ENTRAIDE_CREATE_FAIL = 'ENTRAIDE_CREATE_FAIL'
export const ENTRAIDE_CREATE_RESET = 'ENTRAIDE_CREATE_RESET'


export const ENTRAIDE_DELETE_REQUEST = 'ENTRAIDE_DELETE_REQUEST'
export const ENTRAIDE_DELETE_SUCCESS = 'ENTRAIDE_DELETE_SUCCESS'
export const ENTRAIDE_DELETE_FAIL = 'ENTRAIDE_DELETE_FAIL'



export const ENTRAIDE_LIST_REQUEST = 'ENTRAIDE_LIST_REQUEST'
export const ENTRAIDE_LIST_SUCCESS = 'ENTRAIDE_LIST_SUCCESS'
export const ENTRAIDE_LIST_FAIL = 'ENTRAIDE_LIST_FAIL'



export const ENTRAIDE_DETAILS_REQUEST = 'ENTRAIDE_DETAILS_REQUEST'
export const ENTRAIDE_DETAILS_SUCCESS = 'ENTRAIDE_DETAILS_SUCCESS'
export const ENTRAIDE_DETAILS_FAIL = 'ENTRAIDE_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const ENTRAIDE_UPDATE_REQUEST = 'ENTRAIDE_UPDATE_REQUEST'
export const ENTRAIDE_UPDATE_SUCCESS = 'ENTRAIDE_UPDATE_SUCCESS'
export const ENTRAIDE_UPDATE_FAIL = 'ENTRAIDE_UPDATE_FAIL'
export const ENTRAIDE_UPDATE_RESET = 'ENTRAIDE_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'

export const ENTRAIDE_UPDATE_STATUS_REQUEST = 'ENTRAIDE_UPDATE_STATUS_REQUEST';
export const ENTRAIDE_UPDATE_STATUS_SUCCESS = 'ENTRAIDE_UPDATE_STATUS_SUCCESS';
export const ENTRAIDE_UPDATE_STATUS_FAIL = 'ENTRAIDE_UPDATE_STATUS_FAIL';

// actionTypes.js
export const UPDATE_ENTRAIDE_STATUS_REQUEST = "UPDATE_ENTRAIDE_STATUS_REQUEST";
export const UPDATE_ENTRAIDE_STATUS_SUCCESS = "UPDATE_ENTRAIDE_STATUS_SUCCESS";
export const UPDATE_ENTRAIDE_STATUS_FAILURE = "UPDATE_ENTRAIDE_STATUS_FAILURE";