export const ENTRETIEN_CREATE_REQUEST = 'ENTRETIEN_CREATE_REQUEST'
export const ENTRETIEN_CREATE_SUCCESS = 'ENTRETIEN_CREATE_SUCCESS'
export const ENTRETIEN_CREATE_FAIL = 'ENTRETIEN_CREATE_FAIL'
export const ENTRETIEN_CREATE_RESET = 'ENTRETIEN_CREATE_RESET'


export const ENTRETIEN_DELETE_REQUEST = 'ENTRETIEN_DELETE_REQUEST'
export const ENTRETIEN_DELETE_SUCCESS = 'ENTRETIEN_DELETE_SUCCESS'
export const ENTRETIEN_DELETE_FAIL = 'ENTRETIEN_DELETE_FAIL'



export const ENTRETIEN_LIST_REQUEST = 'ENTRETIEN_LIST_REQUEST'
export const ENTRETIEN_LIST_SUCCESS = 'ENTRETIEN_LIST_SUCCESS'
export const ENTRETIEN_LIST_FAIL = 'ENTRETIEN_LIST_FAIL'



export const ENTRETIEN_DETAILS_REQUEST = 'ENTRETIEN_DETAILS_REQUEST'
export const ENTRETIEN_DETAILS_SUCCESS = 'ENTRETIEN_DETAILS_SUCCESS'
export const ENTRETIEN_DETAILS_FAIL = 'ENTRETIEN_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const ENTRETIEN_UPDATE_REQUEST = 'ENTRETIEN_UPDATE_REQUEST'
export const ENTRETIEN_UPDATE_SUCCESS = 'ENTRETIEN_UPDATE_SUCCESS'
export const ENTRETIEN_UPDATE_FAIL = 'ENTRETIEN_UPDATE_FAIL'
export const ENTRETIEN_UPDATE_RESET = 'ENTRETIEN_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'

export const ENTRETIEN_UPDATE_STATUS_REQUEST = 'ENTRETIEN_UPDATE_STATUS_REQUEST';
export const ENTRETIEN_UPDATE_STATUS_SUCCESS = 'ENTRETIEN_UPDATE_STATUS_SUCCESS';
export const ENTRETIEN_UPDATE_STATUS_FAIL = 'ENTRETIEN_UPDATE_STATUS_FAIL';

// actionTypes.js
export const UPDATE_ENTRETIEN_STATUS_REQUEST = "UPDATE_ENTRETIEN_STATUS_REQUEST";
export const UPDATE_ENTRETIEN_STATUS_SUCCESS = "UPDATE_ENTRETIEN_STATUS_SUCCESS";
export const UPDATE_ENTRETIEN_STATUS_FAILURE = "UPDATE_ENTRETIEN_STATUS_FAILURE";