export const PERMACULTURE_CREATE_REQUEST = 'PERMACULTURE_CREATE_REQUEST'
export const PERMACULTURE_CREATE_SUCCESS = 'PERMACULTURE_CREATE_SUCCESS'
export const PERMACULTURE_CREATE_FAIL = 'PERMACULTURE_CREATE_FAIL'
export const PERMACULTURE_CREATE_RESET = 'PERMACULTURE_CREATE_RESET'


export const PERMACULTURE_DELETE_REQUEST = 'PERMACULTURE_DELETE_REQUEST'
export const PERMACULTURE_DELETE_SUCCESS = 'PERMACULTURE_DELETE_SUCCESS'
export const PERMACULTURE_DELETE_FAIL = 'PERMACULTURE_DELETE_FAIL'



export const PERMACULTURE_LIST_REQUEST = 'PERMACULTURE_LIST_REQUEST'
export const PERMACULTURE_LIST_SUCCESS = 'PERMACULTURE_LIST_SUCCESS'
export const PERMACULTURE_LIST_FAIL = 'PERMACULTURE_LIST_FAIL'



export const PERMACULTURE_DETAILS_REQUEST = 'PERMACULTURE_DETAILS_REQUEST'
export const PERMACULTURE_DETAILS_SUCCESS = 'PERMACULTURE_DETAILS_SUCCESS'
export const PERMACULTURE_DETAILS_FAIL = 'PERMACULTURE_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const PERMACULTURE_UPDATE_REQUEST = 'PERMACULTURE_UPDATE_REQUEST'
export const PERMACULTURE_UPDATE_SUCCESS = 'PERMACULTURE_UPDATE_SUCCESS'
export const PERMACULTURE_UPDATE_FAIL = 'PERMACULTURE_UPDATE_FAIL'
export const PERMACULTURE_UPDATE_RESET = 'PERMACULTURE_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'

export const PERMACULTURE_UPDATE_STATUS_REQUEST = 'PERMACULTURE_UPDATE_STATUS_REQUEST';
export const PERMACULTURE_UPDATE_STATUS_SUCCESS = 'PERMACULTURE_UPDATE_STATUS_SUCCESS';
export const PERMACULTURE_UPDATE_STATUS_FAIL = 'PERMACULTURE_UPDATE_STATUS_FAIL';

// actionTypes.js
export const UPDATE_PERMACULTURE_STATUS_REQUEST = "UPDATE_PERMACULTURE_STATUS_REQUEST";
export const UPDATE_PERMACULTURE_STATUS_SUCCESS = "UPDATE_PERMACULTURE_STATUS_SUCCESS";
export const UPDATE_PERMACULTURE_STATUS_FAILURE = "UPDATE_PERMACULTURE_STATUS_FAILURE";