export const SANTE_CREATE_REQUEST = 'SANTE_CREATE_REQUEST'
export const SANTE_CREATE_SUCCESS = 'SANTE_CREATE_SUCCESS'
export const SANTE_CREATE_FAIL = 'SANTE_CREATE_FAIL'
export const SANTE_CREATE_RESET = 'SANTE_CREATE_RESET'


export const SANTE_DELETE_REQUEST = 'SANTE_DELETE_REQUEST'
export const SANTE_DELETE_SUCCESS = 'SANTE_DELETE_SUCCESS'
export const SANTE_DELETE_FAIL = 'SANTE_DELETE_FAIL'



export const SANTE_LIST_REQUEST = 'SANTE_LIST_REQUEST'
export const SANTE_LIST_SUCCESS = 'SANTE_LIST_SUCCESS'
export const SANTE_LIST_FAIL = 'SANTE_LIST_FAIL'



export const SANTE_DETAILS_REQUEST = 'SANTE_DETAILS_REQUEST'
export const SANTE_DETAILS_SUCCESS = 'SANTE_DETAILS_SUCCESS'
export const SANTE_DETAILS_FAIL = 'SANTE_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const SANTE_UPDATE_REQUEST = 'SANTE_UPDATE_REQUEST'
export const SANTE_UPDATE_SUCCESS = 'SANTE_UPDATE_SUCCESS'
export const SANTE_UPDATE_FAIL = 'SANTE_UPDATE_FAIL'
export const SANTE_UPDATE_RESET = 'SANTE_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'

export const SANTE_UPDATE_STATUS_REQUEST = 'SANTE_UPDATE_STATUS_REQUEST';
export const SANTE_UPDATE_STATUS_SUCCESS = 'SANTE_UPDATE_STATUS_SUCCESS';
export const SANTE_UPDATE_STATUS_FAIL = 'SANTE_UPDATE_STATUS_FAIL';

// actionTypes.js
export const UPDATE_SANTE_STATUS_REQUEST = "UPDATE_SANTE_STATUS_REQUEST";
export const UPDATE_SANTE_STATUS_SUCCESS = "UPDATE_SANTE_STATUS_SUCCESS";
export const UPDATE_SANTE_STATUS_FAILURE = "UPDATE_SANTE_STATUS_FAILURE";