export const VOYAGE_CREATE_REQUEST = 'VOYAGE_CREATE_REQUEST'
export const VOYAGE_CREATE_SUCCESS = 'VOYAGE_CREATE_SUCCESS'
export const VOYAGE_CREATE_FAIL = 'VOYAGE_CREATE_FAIL'
export const VOYAGE_CREATE_RESET = 'VOYAGE_CREATE_RESET'


export const VOYAGE_DELETE_REQUEST = 'VOYAGE_DELETE_REQUEST'
export const VOYAGE_DELETE_SUCCESS = 'VOYAGE_DELETE_SUCCESS'
export const VOYAGE_DELETE_FAIL = 'VOYAGE_DELETE_FAIL'



export const VOYAGE_LIST_REQUEST = 'VOYAGE_LIST_REQUEST'
export const VOYAGE_LIST_SUCCESS = 'VOYAGE_LIST_SUCCESS'
export const VOYAGE_LIST_FAIL = 'VOYAGE_LIST_FAIL'



export const VOYAGE_DETAILS_REQUEST = 'VOYAGE_DETAILS_REQUEST'
export const VOYAGE_DETAILS_SUCCESS = 'VOYAGE_DETAILS_SUCCESS'
export const VOYAGE_DETAILS_FAIL = 'VOYAGE_DETAILS_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'


export const VOYAGE_UPDATE_REQUEST = 'VOYAGE_UPDATE_REQUEST'
export const VOYAGE_UPDATE_SUCCESS = 'VOYAGE_UPDATE_SUCCESS'
export const VOYAGE_UPDATE_FAIL = 'VOYAGE_UPDATE_FAIL'
export const VOYAGE_UPDATE_RESET = 'VOYAGE_UPDATE_RESET'


export const ENVOYER_MAIL_SUCCESS = 'ENVOYER_MAIL_SUCCESS'
export const ENVOYER_MAIL_FAILURE = 'ENVOYER_MAIL_FAILURE'
export const ENVOYER_MAIL_REQUEST = 'ENVOYER_MAIL_REQUEST'

export const ENVOYER_MAIL2_SUCCESS = 'ENVOYER_MAIL2_SUCCESS'
export const ENVOYER_MAIL2_FAILURE = 'ENVOYER_MAIL2_FAILURE'
export const ENVOYER_MAIL2_REQUEST = 'ENVOYER_MAIL2_REQUEST'

export const ENVOYER_MAIL3_SUCCESS = 'ENVOYER_MAIL3_SUCCESS'
export const ENVOYER_MAIL3_FAILURE = 'ENVOYER_MAIL3_FAILURE'
export const ENVOYER_MAIL3_REQUEST = 'ENVOYER_MAIL3_REQUEST'


export const ENVOYER_MAIL4_SUCCESS = 'ENVOYER_MAIL4_SUCCESS'
export const ENVOYER_MAIL4_FAILURE = 'ENVOYER_MAIL4_FAILURE'
export const ENVOYER_MAIL4_REQUEST = 'ENVOYER_MAIL4_REQUEST'


export const ENVOYER_MAIL5_SUCCESS = 'ENVOYER_MAIL5_SUCCESS'
export const ENVOYER_MAIL5_FAILURE = 'ENVOYER_MAIL5_FAILURE'
export const ENVOYER_MAIL5_REQUEST = 'ENVOYER_MAIL5_REQUEST'

export const VOYAGE_UPDATE_STATUS_REQUEST = 'VOYAGE_UPDATE_STATUS_REQUEST';
export const VOYAGE_UPDATE_STATUS_SUCCESS = 'VOYAGE_UPDATE_STATUS_SUCCESS';
export const VOYAGE_UPDATE_STATUS_FAIL = 'VOYAGE_UPDATE_STATUS_FAIL';

// actionTypes.js
export const UPDATE_VOYAGE_STATUS_REQUEST = "UPDATE_VOYAGE_STATUS_REQUEST";
export const UPDATE_VOYAGE_STATUS_SUCCESS = "UPDATE_VOYAGE_STATUS_SUCCESS";
export const UPDATE_VOYAGE_STATUS_FAILURE = "UPDATE_VOYAGE_STATUS_FAILURE";